### ISSUE TITLE
Need to include bug fix release of photutils 0.3 here

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda-contrib#105]
Need to include bug fix release of photutils 0.3 here so that workshop PSF notebook would work properly. c/c @eteq

**Comment by eteq** [comment]
I think the plan is to do a 0.3.1 of photutils down the road a bit to address this?  @larrybradley can confirm

**Comment by pllim** [comment]
Is this a problem for the workshop on Jan 3, @eteq ?

**Comment by justincely** [comment]
@pllim i think this was for the JWST DA workshop at ST - looks like v0.3 is already included.  Unless you've heard otherwise, I think this is closed

**Comment by pllim** [comment]
No, this means a bug fix release on top of 0.3, so theoretically it would be 0.3.1. Anyway, it wasn't an issue for AAS but it still affects PSF photometry stuff.

**Comment by larrybradley** [comment]
I'm not sure why this is an issue here.  The PSF-fitting bug in question was fixed before the JWST DA workshop and simply @eteq had them pull from master in the unconference session.  I was waiting to release `0.3.1` until more PSF-fitting docs were added.

**Comment by pllim** [comment]
Feel free to close if you want. I just opened it in case someone is using AstroConda version and run into that bug.

**Comment by larrybradley** [comment]
I think we can close this (I don't have those permissions).  When the next release of `photutils` is ready of course I'll include it here.  Thanks.
