### ISSUE TITLE
Consider auditing recipes and remove unmaintained packages

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda-contrib#240]
The use case that brought this up was `cube-tools`, which has not been updated for a year, causing conflicts with other package updates (e.g., `astropy`). `cube-tools` was a result of JWST DADF sprints and has not been maintained much since then.

We should not be polluting AstroConda channel with "dead" or experimental packages. Some kind of auditing needs to be put in place to keep this environment clean.

c/c @saraogaz @rendinam @jhunkeler

**Comment by jhunkeler** [comment]
related: #49 

`cube-tools` is part of the data-analysis suite... or was. However, if it doesn't work and will not be receiving updates I'm in favor of deprecating it.

**Comment by pllim** [comment]
Maybe @hcferguson can comment on any planned future development for this package as part of JWST DADF. For now, it is outdated.

**Comment by astrofrog** [comment]
By the way, it may make sense to put experimental packages in a specific label of the astroconda channel, e.g. ``astroconda/label/dev``, so that users don't get these by default

**Comment by jhunkeler** [comment]
@pllim #292 removed a bunch of dead packages. It also purged recipes for packages already in the `defaults` channel to avoid duplicating effort in the future.

(i.e. Many of those recipes were added to astroconda because the package _didn't_ exist in the `defaults` channel back then)

**Comment by pllim** [comment]
Yay!

**Comment by pllim** [comment]
If you think this is fully resolved by #292, feel free to close the issue. Thanks, @jhunkeler !
