### ISSUE TITLE
synphot iraf crash, linux mint

### ISSUE THREAD

**Issue by qssha** [astroconda/astroconda-contrib#259]
iraf and all packages intalled from astroconda, downloaded all synphot-data files, $PYSYN_CDBS path added in bash_profile and crrefer in login.cl
iraf and pyraf works fine, but calcphot always crashes. Example

synphot> calcphot "band(wfpc,f555w)" "rn(bb(5000),band(v),18.6,vegamag)" counts

*** Error in `/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e': free(): invalid next size (fast): 0x0aba7f90 ***
======= Backtrace: =========
/lib/i386-linux-gnu/libc.so.6(+0x67377)[0x55751377]
/lib/i386-linux-gnu/libc.so.6(+0x6d2f7)[0x557572f7]
/lib/i386-linux-gnu/libc.so.6(+0x6dc31)[0x55757c31]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x809b814]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x808b4c7]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x8088832]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x80809a7]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x8078740]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x808294f]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x807d50c]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x807de7e]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x807e83e]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x80636a9]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x80502b0]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x804d5f3]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x815124b]
/home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin/x_synphot.e[0x80ae8a5]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf7)[0x55702637]
======= Memory map: ========
08048000-08395000 r-xp 00000000 08:15 1769463                            /home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin.linux/x_synphot.e
08395000-083b8000 rwxp 0034d000 08:15 1769463                            /home/qssha/miniconda2/envs/iraf27/iraf_extern/stsdas/bin.linux/x_synphot.e
083b8000-0a97c000 rwxp 00000000 00:00 0 
0ab40000-0abbc000 rwxp 00000000 00:00 0                                  [heap]
55614000-55636000 r-xp 00000000 08:15 4980778                            /lib/i386-linux-gnu/ld-2.23.so
55636000-55637000 rwxp 00000000 00:00 0 
55637000-55638000 r-xp 00022000 08:15 4980778                            /lib/i386-linux-gnu/ld-2.23.so
55638000-55639000 rwxp 00023000 08:15 4980778                            /lib/i386-linux-gnu/ld-2.23.so
55639000-5563b000 r--p 00000000 00:00 0                                  [vvar]
5563b000-5563c000 r-xp 00000000 00:00 0                                  [vdso]
5563c000-55660000 rwxp 00000000 00:00 0 
55660000-55668000 r-xp 00000000 08:15 4985888                            /lib/i386-linux-gnu/libnss_compat-2.23.so
55668000-55669000 r-xp 00007000 08:15 4985888                            /lib/i386-linux-gnu/libnss_compat-2.23.so
55669000-5566a000 rwxp 00008000 08:15 4985888                            /lib/i386-linux-gnu/libnss_compat-2.23.so
5566a000-5566b000 rwxp 00000000 00:00 0 
5566f000-556c2000 r-xp 00000000 08:15 4985896                            /lib/i386-linux-gnu/libm-2.23.so
556c2000-556c3000 r-xp 00052000 08:15 4985896                            /lib/i386-linux-gnu/libm-2.23.so
556c3000-556c4000 rwxp 00053000 08:15 4985896                            /lib/i386-linux-gnu/libm-2.23.so
556c4000-556dd000 r-xp 00000000 08:15 4980920                            /lib/i386-linux-gnu/libpthread-2.23.so
556dd000-556de000 r-xp 00018000 08:15 4980920                            /lib/i386-linux-gnu/libpthread-2.23.so
556de000-556df000 rwxp 00019000 08:15 4980920                            /lib/i386-linux-gnu/libpthread-2.23.so
556df000-556e1000 rwxp 00000000 00:00 0 
556e1000-556e8000 r-xp 00000000 08:15 4985875                            /lib/i386-linux-gnu/librt-2.23.so
556e8000-556e9000 r-xp 00006000 08:15 4985875                            /lib/i386-linux-gnu/librt-2.23.so
556e9000-556ea000 rwxp 00007000 08:15 4985875                            /lib/i386-linux-gnu/librt-2.23.so
556ea000-5589a000 r-xp 00000000 08:15 4985903                            /lib/i386-linux-gnu/libc-2.23.so
5589a000-5589c000 r-xp 001af000 08:15 4985903                            /lib/i386-linux-gnu/libc-2.23.so
5589c000-5589d000 rwxp 001b1000 08:15 4985903                            /lib/i386-linux-gnu/libc-2.23.so
5589d000-558a1000 rwxp 00000000 00:00 0 
558a1000-558ac000 r-xp 00000000 08:15 4980782                            /lib/i386-linux-gnu/libnss_files-2.23.so
558ac000-558ad000 r-xp 0000a000 08:15 4980782                            /lib/i386-linux-gnu/libnss_files-2.23.so
558ad000-558ae000 rwxp 0000b000 08:15 4980782                            /lib/i386-linux-gnu/libnss_files-2.23.so
558ae000-55911000 rwxp 00000000 00:00 0 
55942000-55959000 r-xp 00000000 08:15 4980773                            /lib/i386-linux-gnu/libnsl-2.23.so
55959000-5595a000 r-xp 00016000 08:15 4980773                            /lib/i386-linux-gnu/libnsl-2.23.so
5595a000-5595b000 rwxp 00017000 08:15 4980773                            /lib/i386-linux-gnu/libnsl-2.23.so
5595b000-5595d000 rwxp 00000000 00:00 0 
5595d000-55968000 r-xp 00000000 08:15 4982075                            /lib/i386-linux-gnu/libnss_nis-2.23.so
55968000-55969000 r-xp 0000a000 08:15 4982075                            /lib/i386-linux-gnu/libnss_nis-2.23.so
55969000-5596a000 rwxp 0000b000 08:15 4982075                            /lib/i386-linux-gnu/libnss_nis-2.23.so
5596a000-55986000 r-xp 00000000 08:15 4982077                            /lib/i386-linux-gnu/libgcc_s.so.1
55986000-55987000 rwxp 0001b000 08:15 4982077                            /lib/i386-linux-gnu/libgcc_s.so.1
55a00000-55a21000 rwxp 00000000 00:00 0 
55a21000-55b00000 ---p 00000000 00:00 0 
fff70000-fff91000 rwxp 00000000 00:00 0                                  [stack]
ERROR: abort

How i can fix this?

**Comment by pllim** [comment]
synphot package in IRAF is not supported anymore. Please use the Python version documented at https://pysynphot.readthedocs.io/en/latest/ . You can install it like this:
```
conda install pysynphot
```

**Comment by qssha** [comment]
thank you!
