### ISSUE TITLE
Python not picking up stginga from this channel

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda-contrib#35]
I pulled Ginga and `stginga` from AstroConda channel but Python cannot find them in an interactive Python session. However, it picks up the command line scripts.

```python
>>> import ginga  # From AstroConda channel
ImportError: No module named 'ginga'
>>> import stginga  # From AstroConda channel
ImportError: No module named 'stginga'
>>> import scipy  # From default Anaconda channel
>>> import astropy  # From default Anaconda channel
>>> astropy.__file__
'.../anaconda/envs/wssenv/lib/python3.5/site-packages/astropy/__init__.py'
>>> sys.path
['',
 '.../anaconda/envs/wssenv/lib/python35.zip',
 '.../anaconda/envs/wssenv/lib/python3.5',
 '.../anaconda/envs/wssenv/lib/python3.5/plat-linux',
 '.../anaconda/envs/wssenv/lib/python3.5/lib-dynload',
 '.../anaconda/envs/wssenv/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg',
 '.../anaconda/envs/wssenv/lib/python3.5/site-packages']
```

```bash
> which python
.../anaconda/envs/wssenv/bin/python
> which ginga
.../anaconda/envs/wssenv/bin/ginga
> which stginga
.../anaconda/envs/wssenv/bin/stginga
> which fitsinfo  # Astropy
.../anaconda/envs/wssenv/bin/fitsinfo
```

Here are the contents inside installation directory:

```bash
> ls .../anaconda/envs/wssenv/lib/python3.5/site-packages/ | grep ginga
ginga-2.5.20160627100500-py3.5.egg/
stginga-0.1.1.dev192-py3.5.egg/
> ls .../anaconda/envs/wssenv/lib/python3.5/site-packages/ | grep astropy
astropy/
astropy-1.2.1-py3.5.egg-info/
```

This problem does not exist if I use `pip` or install from source.

Also, for Ginga, I force delete `../anaconda/pkgs/ginga*` and then tried `conda install ginga` from AstroConda again, and this time I can import `ginga`. But the same trick does not work for `stginga`.

**Comment by pllim** [comment]
Update: Don't have this problem using `pip install ginga` in the same environment.

**Comment by pllim** [comment]
In `stginga`'s YAML file, I notice there is a test at the bottom that looks like it is going to try importing `stginga` -- Is it passing?

**Comment by pllim** [comment]
@jhunkeler , is this theoretically fixed?

**Comment by jhunkeler** [comment]
Theoretically yes. I remember it working for me after I fixed it. Can you confirm on your end?

**Comment by pllim** [comment]
I have guinea pigs doing this soon. Will let you know!

**Comment by jhunkeler** [comment]
*Nods* I'll be monitoring this thread

**Comment by pllim** [comment]
Seems to work. Thanks!
