### ISSUE TITLE
Python 3.7 is out

### ISSUE THREAD

**Issue by joseph-long** [astroconda/astroconda-contrib#391]
Tried to upgrade to Python 3.7.0 and found a conflict here:

```
$ conda install python=3.7
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - pysiaf -> python[version='>=2.7,<2.8.0a0']
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.
```

Not sure why it's showing the Python 2.7 constraints. I have `pysiaf                    0.1.8                    py36_0    http://ssb.stsci.edu/astroconda` installed per `conda list`.

**Comment by joseph-long** [comment]
Thanks @jhunkeler! Doing all right here, hope you are too :cactus:

**Comment by pllim** [comment]
I don't think this is an issue anymore. Please close.
