### ISSUE TITLE
Cannot install ci-watson from this channel

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda-contrib#401]
Why is this failing? I see `ci-watson` in the recipes... I tried in both Python 3.6 and 3.7 environments. `pip install ci-watson` works fine.

```
$ conda install ci-watson
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ci-watson

Current channels:

  - http://ssb.stsci.edu/astroconda/linux-64
  - http://ssb.stsci.edu/astroconda/noarch
  - https://conda.anaconda.org/astropy/linux-64
  - https://conda.anaconda.org/astropy/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch
```

**Comment by rendinam** [comment]
There are two steps to adding a package to the astroconda channel.
* Create recipe in https://github.com/astroconda/astroconda-contrib
* Add package name to the `public.yaml` build manifest in https://github.com/astroconda/build_manifests

`ci-watson` is now in the build manifest and the packages have been built and published on the Astroconda public channel.

**Comment by pllim** [comment]
Thanks! I did not know about that second step. Is it documented anywhere?
