### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Ragadeepika-Pucha** [astroconda/astroconda-contrib#489]
Hi - I am getting this error - 
ModuleNotFoundError: No module named 'stsci.tools'

But, the module is in my path and i have also tried updating all. Its still showing the error. Please let me know what to do.

**Comment by joseph-long** [comment]
I was helping @Ragadeepika-Pucha with this and noticed something odd. The `site-packages` folder contains an `stsci/` folder, as well as `stsci.<name...>.egg` folders and corresponding `.pth` files. However, when importing `drizzlepac` it showed the error she included above.

Going into the `.egg` folders and copying the contents of the `stsci/` subfolder in each to the `stsci/` folder in `site-packages/` allowed `import drizzlepac` to succeed, though it did emit some warnings about lacking dependencies for tweakreg.

Is this an AstroConda issue? I'm working on reproducing locally (macOS 10.14.3, Python 3.7, conda 4.6.1).

**Comment by joseph-long** [comment]
cc @jhunkeler

**Comment by jhunkeler** [comment]
Fixed by #491

**Comment by joseph-long** [comment]
Cheers, thank you!

@Ragadeepika-Pucha so, to fix this you can undo what I did (by removing `site-packages/stsci/tools`, `site-packages/stsci/convolve`, and `site-packages/stsci/ndimage`) and `conda update --all`. Or you can just delete and recreate the astroconda environment in an hour or two when the new packages get posted.

**Comment by joseph-long** [comment]
@jhunkeler could you drop a comment here when the channel updates? Thanks!

**Comment by jhunkeler** [comment]
@joseph-long @Ragadeepika-Pucha Go ahead and try now.

**Comment by joseph-long** [comment]
Confirmed fixed on my end 👍

**Comment by Ragadeepika-Pucha** [comment]
Its working now. Thank you.
