### ISSUE TITLE
Need to update PyRAF to 2.1.11

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda-contrib#52]
This might solve FootPrints Ticket 9178. But I am not familiar with all its dependencies enough to update the YAML myself. I don't know what exactly changed between 2.1.10 and 2.1.11.

c/c @jhunkeler and @cdsontag

**Comment by cdsontag** [comment]
Actually, 9178 looks to me like he just doesn't have his IRAF environment set up yet.  It can't find a basic startup file.

**Comment by cdsontag** [comment]
But yes, even if it is not the fix, we should of course update this to pyraf v2.1.11 anyway.
