### ISSUE TITLE
Synphot 0.2.1 conda package does not play along well with pip

### ISSUE THREAD

**Issue by hugobuddel** [astroconda/astroconda-contrib#592]
The conda package of synphot 0.2.0 worked well with pip. E.g.:

````
$ conda install "python >=3.7" "synphot =0.2.0"
$ pip install "synphot>0.1"

Requirement already satisfied: synphot>0.1 in [...]/lib/python3.8/site-packages (0.2.0)
````

However, 0.2.1 conda does not get along well with pip. E.g.:

````
$ conda install "python >=3.7" "synphot =0.2.1"
$ pip install "synphot>0.1"

[...]
Collecting synphot>0.1
Installing collected packages: synphot
  Found existing installation: synphot 0.0.0
    Uninstalling synphot-0.0.0:
      Successfully uninstalled synphot-0.0.0
Successfully installed synphot-0.2.1
````

In reality, this is triggered by me having one conda dependency that requires just synphot, and a pip dependency that requires "synphot>0.1". E.g.
````
conda install something_that_requires_synphot
pip install something_that_requires_synphot_gt_0_1
````
And in my case it will actually try to compile synphot 0.2.1 and fail because gcc is not installed on our CI image.

My guess is that the different behavior between 0.2.0 and 0.2.1 has to do with differences in the autogenerated `version.py`:
![synphotversions](https://user-images.githubusercontent.com/1306453/72436631-ce110500-3798-11ea-9614-1082df8d6dbb.png)

The 0.2.0 version.py has major/minor/bugfix explicitly set, while the 0.2.1 version only has the version as a string. This might result in pip not knowing the correct version number; but I'm not sure about how the interaction between conda - pip works.

Maybe this is related to #591?

Possible fixes:

- (On me, workaround): Hardcode synphot 0.2.0 as a dependency for now.
- (On me, proper): Ensure there are conda packages for everything I need.
- Ensure conda package of synphot 0.2.1 plays along properly with pip. There seems other information in the version.py of 0.2.0 that might be useful to keep around, like the commit hash. But I wouldn't know where to begin.

**Comment by rendinam** [comment]
@pllim

**Comment by pllim** [comment]
O.2.1 uses setuptools_scm to generate version. On hindsight, maybe I should have made it a major release, ah well.

Although, are you sure conda actually installed synphot 0.2.1 as you pinned above? I can't tell because you didn't provide a full log. synphot release on both astroconda and conda-forge were just fixed in the last 24 hours, so conda might not even have it yet when you tried.

**Comment by rendinam** [comment]
Also, which version of conda are you using?

**Comment by hugobuddel** [comment]
It has 0.2.1. I noticed it because our continuous integration does a full install, and thus fetched the new version this morning.

(This is kinda on purpose, so we catch problems with dependencies sooner rather than later. But maybe we should just hardcode more versions.)

I'm not sure how much energy you should spend to fix this, because people should perhaps not mix conda and pip.

Here is the full log:

conda versoin:
````
$ conda --version
conda 4.8.0
````

conda install:
````
$ conda install "python >=3.7" "synphot =0.2.1"
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: [...]/miniconda3/envs/synphottest

  added / updated specs:
    - python[version='>=3.7']
    - synphot=0.2.1


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  astropy            conda-forge/linux-64::astropy-4.0-py38h516909a_0
  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/label/pre-3.8/linux-64::certifi-2019.3.9-py38_0
  hypothesis         conda-forge/noarch::hypothesis-5.1.5-py_0
  importlib_metadata conda-forge/linux-64::importlib_metadata-1.4.0-py38_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_4
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  more-itertools     conda-forge/noarch::more-itertools-8.1.0-py_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  numpy              conda-forge/linux-64::numpy-1.17.3-py38h95a1406_0
  openssl            conda-forge/linux-64::openssl-1.1.1d-h516909a_0
  packaging          conda-forge/noarch::packaging-20.0-py_0
  pip                conda-forge/label/pre-3.8/linux-64::pip-19.1-py38_0
  pluggy             conda-forge/linux-64::pluggy-0.13.1-py38_0
  psutil             conda-forge/linux-64::psutil-5.6.7-py38h516909a_0
  py                 conda-forge/noarch::py-1.8.1-py_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  pytest             conda-forge/linux-64::pytest-5.3.2-py38_0
  pytest-arraydiff   conda-forge/noarch::pytest-arraydiff-0.3-py_0
  pytest-astropy     conda-forge/noarch::pytest-astropy-0.7.0-py_0
  pytest-astropy-he~ conda-forge/noarch::pytest-astropy-header-0.1.2-py_0
  pytest-doctestplus conda-forge/noarch::pytest-doctestplus-0.4.0-py_0
  pytest-openfiles   conda-forge/noarch::pytest-openfiles-0.4.0-py_0
  pytest-remotedata  conda-forge/noarch::pytest-remotedata-0.3.1-py_0
  python             conda-forge/linux-64::python-3.8.1-h357f687_1
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  scipy              conda-forge/linux-64::scipy-1.4.1-py38h921218d_0
  setuptools         conda-forge/label/pre-3.8/linux-64::setuptools-41.0.1-py38_0
  six                conda-forge/label/pre-3.8/linux-64::six-1.12.0-py38_1000
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.1.0-py_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  synphot            conda-forge/linux-64::synphot-0.2.1-py38hc1659b7_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  wcwidth            conda-forge/noarch::wcwidth-0.1.8-py_0
  wheel              conda-forge/label/pre-3.8/linux-64::wheel-0.33.1-py38_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zipp               conda-forge/noarch::zipp-1.0.0-py_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
````

pip install:
````
$ pip install "synphot>0.1"
Collecting synphot>0.1
Requirement already satisfied: scipy in [...]/miniconda3/envs/synphottest/lib/python3.8/site-packages (from synphot>0.1) (1.4.1)
Requirement already satisfied: astropy>=2 in [...]/miniconda3/envs/synphottest/lib/python3.8/site-packages (from synphot>0.1) (4.0)
Requirement already satisfied: numpy>=1.16 in [...]/miniconda3/envs/synphottest/lib/python3.8/site-packages (from synphot>0.1) (1.17.3)
Installing collected packages: synphot
  Found existing installation: synphot 0.0.0
    Uninstalling synphot-0.0.0:
      Successfully uninstalled synphot-0.0.0
Successfully installed synphot-0.2.1
````

**Comment by pllim** [comment]
> I'm not sure how much energy you should spend to fix this, because people should perhaps not mix conda and pip.

I am not sure either. It is weird that `pip` is behaving as such because supposedly `setuptools_scm` is the correct way to do versioning nowadays, as opposed to hardcoding version as before. Regardless, I agree that `pip` has never played well with `conda` historically even outside of this issue.

Hopefully this is a one-time growing pain for switching versioning to `setuptools_scm`. That is, in a future release, it would be self-consistent again.

For now, let's chalk this as won't fix. But if you see the same problem again with `>=0.2.2` in the future, please open issue at https://github.com/spacetelescope/synphot_refactor/issues instead.

Thank you for reporting this!

**Comment by pllim** [comment]
Actually, @astrofrog pointed out this is indeed a bug in the `conda` packaging. `conda` is generating `synphot-0.0.0.dist-info` directory, which caused what you were seeing above. @rendinam will add `setuptools_scm` as a `conda-build` dependency and report back. 😬

**Comment by rendinam** [comment]
A new `synphot 0.2.1` has been built and published to the astroconda channel. Please try again to verify that the problematic behavior has been resolved.

**Comment by hugobuddel** [comment]
Thanks @pllim and @rendinam! It works nicely now. I'll use your code as an example on how to create conda packages. (By the way, are you all on some gitter/slack/riot/discord or something?)

**Comment by pllim** [comment]
@hugobuddel , for `astroconda`, not really. But `synphot` is an Astropy affiliated package, and Astropy has its own Slack at http://joinslack.astropy.org/ . 😸
