### ISSUE TITLE
Where can I set PYTHONPATH from?

### ISSUE THREAD

**Issue by mgennaro** [astroconda/astroconda-contrib#77]
Hi, 
when I first moved to python and in particular, anaconda (and astroconda) I learned that I could add a myenv.sh file in the directory:

anaconda3/envs/astroconda/etc/conda/activate.d/

that gets sourced when I do 

source activate astroconda

This file allows me to add my own packages to that particular environment.
However when I recently installed astroconda on a new machine, I realized that the activate.d directory is no longer created.
I understand this is a choice related to the choice of not installing the webbpsf packeg by default, given its size, but still I do not understand why the activate.d directory itself should no longer be there.

The anaconda3/bin/activate script still looks for it, so why remove it?
If there is a good reason for removing it, could you please provide explanations on how one could 
have access to one's own packages within the astroconda environment (i.e. how do I set pythonpath at startup for the astroconda environment only?)

Thanks,
Mario

**Comment by jhunkeler** [comment]
Hi @mgennaro,

The `[...]/etc/conda/[de]activate.d/` directory  is a built-in feature of conda and is used by a few of our packages as a matter of convenience. If no packages take advantage of this feature, the directory will not be generated. I agree it would be great if the directory existed regardless if package maintainers took advantage of this or not. It would save me, you and everybody we know from looking up the location/naming-convention every time I wanted to implement it.

The documentation regarding this feature and its use can be found here:
http://conda.pydata.org/docs/using/envs.html#saved-environment-variables

**anaconda3/envs/astroconda/etc/conda/activate.d/mgennaro.sh:**
```bash
# Save old path
export PYTHONPATH_OLD="$PYTHONPATH"

# Use a new path
export PYTHONPATH="/path/to/static/modules"
```

**anaconda3/envs/astroconda/etc/conda/deactivate.d/mgennaro.sh:**
```bash
# Restore the old path
export PYTHONPATH="$PYTHONPATH_OLD"

# Destroy the temporary variable
unset PYTHONPATH_OLD
```

However, I don't recommend using `PYTHONPATH` for managing access to your personal code, and I'm not convinced this activate/deactivate method is a good idea in the long-term. You probably will want to create native python packages for your code and install them into your environment.

`python setup.py develop` can be used to "install" code you're actively working on, but without placing it into `site-packages` (where packages normally end up after running `python setup.py install`). 

Below are a few pieces of documentation that will get you started if you wish to start writing python packages:

http://setuptools.readthedocs.io/en/latest/index.html

http://setuptools.readthedocs.io/en/latest/setuptools.html#basic-use

http://setuptools.readthedocs.io/en/latest/setuptools.html#develop-deploy-the-project-source-in-development-mode

**Comment by mgennaro** [comment]
Thanks @jhunkeler,
I feared that was the way to go ;)
I guess I'll have to learn how to write setup.py files.
Thanks for the tip on the develop option, I was not aware of that.

BTW, just my personal feeling: the average astronomer might need a distilled version of those help links you sent me, with few examples on "How to access your own modules (not in the pwd) from within astroconda".
This one may be useful as well:

https://docs.python.org/3/distutils/examples.html

**Comment by pllim** [comment]
@mgennaro , if you want to start writing a package for distribution, Astropy's package template is a good place to start. 

http://docs.astropy.org/en/stable/development/affiliated-packages.html (You can still follow the instructions even if you don't want your package to be really affiliated to Astropy.)

https://github.com/astropy/package-template

**Comment by justincely** [comment]
@mgennaro maybe a topic for a future pylunch, or even focused tutorials for post-docs/astronomers on site.  Installing packages is a bit out of scope for the astroconda docs, but maybe could be added to the tech-staff training materials as a quick intro.

**Comment by pllim** [comment]
It looks like `pandeia` somehow listed `jupyter` as dependency, so that's why it's installed. That same package also listed `ipython-notebook`, so not sure why `notebook` isn't. Maybe all they have to do is to change their dependency listing to `notebook` to solve this issue? @tepickering can clarify.
