### ISSUE TITLE
Cleanup stsci-data-analysis recipe

### ISSUE THREAD

**Issue by justincely** [astroconda/astroconda-contrib#78]
@jhunkeler the specview package isn't necessary anymore and should be removed.  Is the general procedure for removing packages to remove the main recipe folder, and remove references to it from any meta-packages?

And then do the same to astroconda-dev?

**Comment by justincely** [comment]
proposals so far is below.  Add/comment to change things.

1. remove specview
2. remove cube-tools
3. add specviz
4. add photutils
5. add glue
6. add imexam

Is ASV necessary?

**Comment by justincely** [comment]
should also add mosviz when there is a numbered release

**Comment by pllim** [comment]
@justincely , I don't quite understand... All the packages you requested for adding are already there. Also, ASV is a benchmarking tool. It has nothing to do with DADF. We should keep it.

**Comment by pllim** [comment]
Oh, wait... You mean some subset of `astroconda-contrib`? Where can we view that list?

**Comment by justincely** [comment]
yeah, this is the stsci-data-analysis metapackage recipe.  So the things we want the user to get if they were to just want an environment focused on data analysis:

https://github.com/astroconda/astroconda-contrib/blob/master/stsci-data-analysis/meta.yaml is the recipe

**Comment by pllim** [comment]
In that case, `asv` is probably not needed for that particular recipe.

**Comment by justincely** [comment]
@larrybradley can you think of anything else that should be included in the data-analysis metapackage?

**Comment by larrybradley** [comment]
@justincely Yes, `astroimtools` is a DADF sprint product:  https://github.com/spacetelescope/astroimtools

**Comment by justincely** [comment]
thanks, i'll get that in there too

**Comment by jhunkeler** [comment]
@justincely FYI, I just merged Larry's update to photutils (0.2.2 -> 0.3)

**Comment by justincely** [comment]
cool, thanks Joe
