### ISSUE TITLE
Installing astroconda broke my TensorFlow related code

### ISSUE THREAD

**Issue by d80b2t** [astroconda/astroconda-contrib#95]
Hi there, 
I use the Keras neural networks library (https://keras.io/) that is based on Theano and TensorFlow. 

I installed astroconda earlier today, and this broke my Python-Keras code, since I can't now use/import TensorFlow. I've tracked down this directory:
/Users/npr1/astroconda/lib/python3.5/site-packages/keras/backend
but really don't know what to do next. 

Little help??!
Thanks, 
Nic
npross@roe.ac.uk

**Comment by jhunkeler** [comment]
I've never used `keras` before but I am pretty certain AstroConda did not break anything.  Have you installed tensorflow (and/or theano) into that environment?

```
$ conda install -c conda-forge tensorflow
$ conda install theano
```

There also seems to be a little bit of setup involved with this software:
https://keras.io/backend/



Regards,
Joe
